# Site settings
title: Tania Manzanal Cerda
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Illustration and so on. Tania Manzanal Cerda aka cerdineta
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
instagram_username: cerdineta
behance_username: lamansaneta

# Build settings
markdown: kramdown
permalink: pretty

collections:
  blog:
    output: true
